config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Resque::Server.new, at: '/resque'

  root 'static_page#home'
  get 'images', action: :index, controller: 'categories/photos'
  get 'comments', action: :index, controller: 'categories/photos/comments'
  post 'categories/:category_id/photos/:photo_id/comments/:id/edit', action: :edit,
                                                                     controller: 'categories/photos/comments'
  post 'categories/:id/edit', action: :edit, controller: 'categories'
  post 'categories/:category_id/photos/:id/edit', action: :edit, controller: 'categories/photos'

  # patch '/categories/:id/subscribe', action: :subscribe, controller: 'categories'
  # delete '/categories/:id/unsubscribe', action: :unsubscribe, controller: 'categories'
  # patch 'upvote/category/photo', action: :upvote, controller: 'categories/photos'
  devise_for :users

  resources :categories do
    member do
      patch :subscribe
      delete :unsubscribe
    end
    resources :photos, only: %i[show create], module: :categories do
      member do
        patch :upvote
      end
      resources :comments, only: %i[create], module: :photos
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :subscribes, dependent: :destroy

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :title, length: { in: 3..50 }

  extend FriendlyId
  friendly_id :title, use: %i[slugged finders]
end

app/controllers/categories/photos/comments_controller.rb
# frozen_string_literal: true

module Categories
  module Photos
    class CommentsController < ApplicationController
      def index
        @q = Comment.ransack(params[:q])
        @pagy, @comments = pagy(@q.result(distinct: true).order(created_at: :desc), utems: 20)
      end

      def create
        @photo = Photo.find(params[:photo_id])
        @comment = @photo.comments.new(comment_params)
        respond_to do |format|
          if @comment.save
            format.turbo_stream do
              render turbo_stream: [
                turbo_stream.prepend("photo_comment_#{@photo.id}", partial: 'categories/photos/comments/comment',
                                                             locals: { comment: @comment })
              ]
            end
          else
            render_turbo_stream_error
            format.turbo_stream do
              render turbo_stream: [
                turbo_stream.prepend("comment_errors_#{@photo.id}", partial: 'shared/flash')
              ]
            end
          end
        end
      end

      private

      def render_turbo_stream_error
        flash.now[:alert] = @comment.errors.full_messages.join(';')
      end

      def comment_params
        params.require(:comment).permit(:body).merge(user: current_user)
      end
    end
  end
end

app/controllers/categories/photos_controller.rb
# frozen_string_literal: true

module Categories
  class PhotosController < ApplicationController
    before_action :set_category, only: %i[upvote create]

    def upvote
      @photo = @category.photos.find(params[:id])
      @photo.upvote! current_user
      redirect_to request.referer
    end

    def index
      @q = Photo.ransack(params[:q])
      @pagy, @photos = pagy(@q.result(distinct: true).order(cached_votes_total: :desc), items: 18)
    end

    def create
      @photo = @category.photos.new(photo_params)
      respond_to do |format|
        if @photo.save
          User.find_each do |user|
            @category.subscribes.each do |subscribe|
              if subscribe.category_id == @category.id.to_s && subscribe.user_id == user.id.to_s
                PhotoCreateJob.perform_later(user, subscribe, current_user)
              end
            end
          end

          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update('new_photo', partial: 'categories/photos/form', locals: { photo: Photo.new })
            ]
          end
        else
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update('new_photo', partial: 'categories/photos/form', locals: { photo: @photo })
            ]
          end
        end
      end
    end

    private

    def set_category
      @category = Category.find(params[:category_id])
    end

    def photo_params
      params.require(:photo).permit(:image).merge(user: current_user)
    end
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show subscribe unsubscribe edit update destroy]

  def index
    @q = Category.ransack(params[:q])
    @pagy, @categories = pagy(@q.result(distinct: true).order(title: :asc), items: 12)
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update(@category, partial: 'categories/form', locals: { category: @category })
        ]
      end
    end
  end

  def create
    @category = current_user.categories.new(category_params)
    respond_to do |format|
      if @category.save
        flash.now[:notice] = 'Category was successfully created.'
      else
        render_turbo_stream_error
      end
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.prepend('flash', partial: 'shared/flash')
        ]
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update(@category, partial: 'categories/category', locals: { category: @category })
          ]
        end
      else
        render_turbo_stream_error
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.prepend('flash', partial: 'shared/flash')
          ]
        end
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  def subscribe
    @subscribe = current_user.subscribes.new
    @subscribe.category_id = @category.id
    @subscribe.user_id = current_user.id
    respond_to do |format|
      if @subscribe.save
        CategorySubscribeJob.perform_later(current_user, @subscribe)
        format.html { redirect_to categories_url, notice: 'Subscribe was successfully created.' }
      else
        format.html { redirect_to categories_url, notice: 'You are already subscribed to the category!' }
      end
    end
  end

  def unsubscribe
    @subscribe = current_user.subscribes.find_by(category_id: @category.id)
    @subscribe.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Unsubscribe!' }
    end
  end

  private

  def render_turbo_stream_error
    flash.now[:alert] = @category.errors.full_messages.join(';')
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :user_id)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="card border border-secondary shadow-0 mb-3" id="<%= dom_id category %>">
  <%= link_to  category do %>
    <% if category.photos.first.present? %>
      <%= image_tag (category.photos.first.image.url), class:"card-img-top" %>
    <% end %>
    <div class="card-header text-center text-dark">
      <%= category.title.capitalize %>
    </div>
  <% end %>
  
  <div class="card-body">
    <div class="row text-dark">
      <div class="col-sm-6 text-center">
        <% if category.user.id == current_user.id %>
          <button type="button" class="btn btn-outline-dark dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" >
            Settings
            <span class="visually-hidden">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
            <li><%= button_to "Edit ", edit_category_path(category), method: :post, class:"dropdown-item" %></li>
            <li><%= button_to "Destroy ", category, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class:"dropdown-item" %></li>
          </ul>
        <% else %>
          <div class="form-control-plaintext">
            <%= category.user.email %>
          </div>
        <% end %>
      </div>
      <div class="col-sm-6 text-center">
        <div class="btn-group">
          <% unless category.subscribes.find_by(user_id: current_user.id).present? %>
            <%= button_to "Subscribe", [:subscribe, category], method: :patch, data: {turbo: "false"}, class:"btn btn-outline-success" %>
          <% else %>
            <%= button_to "Unsubscribe", [:unsubscribe, category], method: :delete, data: {turbo: "false"}, class:"btn btn-outline-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= turbo_frame_tag category do %>
  <%= form_with(model: category) do |form| %>
    <%= render 'shared/errors', form: form %>
    <div class="field">
      <%= form.text_field :title, placeholder: "Name:", class:"form-control" %>
    </div>
    <%= form.submit class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/categories/_modal.html.erb
<%= turbo_frame_tag category do %>
  <div data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd">
    <%= form_with(model: category) do |form| %>
      <div class="modal fade" id="newCategory" data-bs-backdrop="false" aria-labelledby="newCategory" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="lolLabel">New Category</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <div class="field">
                  <%= form.text_field :title, placeholder: "Name:" %>
                </div>
              </div>
              <div class="modal-footer">
                <%= form.submit class: "btn btn-primary" %>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="card text-center border-secondary mt-3">
  <%= search_form_for @q do |f| %>
    <div class="input-group ">
      <%= f.search_field :title_cont,placeholder:"Search category:", class:"form-control rounded" %>
      <%= f.submit class:"btn btn-outline-primary" %>
    </div>
    <ul class="pagination mt-2">
      <li class="page-item disabled">
        <div class="page-link">Sort by:</div>
      </li>
      <li class="page-item page-link"><%= sort_link(@q, :title) %></li>
      <li class="page-item page-link"><%= sort_link(@q, :created_at) %></li>
      <li class="page-item page-link"><%= sort_link(@q, :photos_count) %></li>
    </ul>
  <% end %>
</div>
<div id="category">
  <div class="row row-cols-4 mt-5">
    <% @categories.each do |category| %>
      <div class="col">
        <%= render category %><br>
      </div>
    <% end %>
  </div> 
</div>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/categories/show.html.erb
<div class="card text-center border-secondary mt-2">
  <h4 class="card-header">
    <%= @category.title.capitalize %>
  </h4>
  <div class="card-body">
    <div id="new_photo">
      <%= render 'categories/photos/form', photo: @category.photos.new %>
    </div>
  </div>
</div>
<div class="row row-cols-3 mt-3">
  <% @category.photos.order(cached_votes_total: :desc).each do |photo| %>
    <div id="photo" class="col" >
      <%= render partial: "categories/photos/photo", locals: {photo: photo } %>       
    </div>
  <% end %>
</div>