config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Resque::Server.new, at: '/resque'

  root 'static_page#home'
  get 'images', action: :index, controller: 'categories/photos'
  get 'comments', action: :index, controller: 'categories/photos/comments'
  post 'categories/:category_id/photos/:photo_id/comments/:id/edit', action: :edit,
                                                                     controller: 'categories/photos/comments'
  post 'categories/:id/edit', action: :edit, controller: 'categories'
  post 'categories/:category_id/photos/:id/edit', action: :edit, controller: 'categories/photos'

  # patch '/categories/:id/subscribe', action: :subscribe, controller: 'categories'
  # delete '/categories/:id/unsubscribe', action: :unsubscribe, controller: 'categories'
  # patch 'upvote/category/photo', action: :upvote, controller: 'categories/photos'
  devise_for :users

  resources :categories do
    member do
      patch :subscribe
      delete :unsubscribe
    end
    resources :photos, only: %i[show create], module: :categories do
      member do
        patch :upvote
      end
      resources :comments, only: %i[create], module: :photos
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IGallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-light bg-light navbar-expand-lg border border-dark">
        <div class="container-fluid">
        <%= link_to "IGallery", root_path, class:"navbar-brand" %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <div class="btn-group">
                <%= link_to "Categories", categories_path, class:"nav-link" %>
                <button type="button" class="btn btn-light dropdown-toggle dropdown-toggle-split" id="dropdownMenuReference" data-bs-toggle="dropdown" aria-expanded="false" data-bs-reference="parent">
                  
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuReference">
                <%= link_to "New Category", new_category_path, class:"dropdown-item", data: { bs_toggle: "modal", bs_target: "#newCategory" } %>
                </ul>
              </div>
              <li class="nav-item">
              <li> <%= link_to "Imeges", images_path, class:"nav-link active" %></li>
              </li>
              <li class="nav-item">
              <li> <%= link_to "Comments", comments_path(@comments), class:"nav-link active" %></li>
              </li>
            </ul>
            <form class="d-flex">
              <% if signed_in? %>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item btn btn-outline-info">
                    <%= (image_tag (current_user.avatar.url(:thumb)), style:"height: 30px; weight: 30px;") if current_user.avatar.present? %>
                    <%= link_to current_user.email, edit_user_registration_path, class:"ms-2" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to " Log out", destroy_user_session_path, data: { "turbo_method": :delete, turbo_confirm: "Are you sure?" } , class: "btn btn-outline-danger" %>
                  </li>
                  <% else %>
                  <li class="nav-item">
                    <%= link_to " Log in", new_user_session_path, class: "btn btn-outline-success" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to " Register", new_user_registration_path, class:"btn btn-outline-success" %>
                  </li>
                </ul>
              <% end %>
            </form>
          </div>
        </div>
      </nav>
      <div id="flash">
        <%= render "shared/flash" %>
      </div>
      <div id="new_category">
        <%= render "categories/modal", category: Category.new %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>